"""
Django settings for SkriptNet project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import yaml

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECRET_KEY und Passwörter laden
with open(BASE_DIR + "/SkriptNet/skriptnet_credentials.yaml", 'r') as f:
    skriptnet_credentials = yaml.load(f)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = skriptnet_credentials['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '129.187.206.200', 'skripten.fs04.ee.hm.edu', 'skripten.fs04.de']

# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    # https://docs.djangoproject.com/en/dev/ref/contrib/admin/admindocs/
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party Apps
    'captcha',
    'crispy_forms',
    # http://django-extensions.readthedocs.io/en/latest/graph_models.html
    'django_extensions',

    # My Apps
    'skripten_shop'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SkriptNet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SkriptNet.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        # 'NAME': 'skriptnetdb',
        # 'USER': 'skriptnet',
        # 'PASSWORD': skriptnet_credentials['DATABASE_PW'],
        # 'HOST': 'localhost',
        # 'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static_root/static'
DOCS_ROOT = os.path.join(BASE_DIR, 'docs/_build/html')

LOGIN_URL = '/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures'),
)

# LOGGING Settings
# https://docs.djangoproject.com/en/dev/topics/logging/#topic-logging-parts-filters
#############################################################
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logfiles/skripten_shop.log'),
            'maxBytes': 1024 * 1024 * 1,  # 1MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },

    'formatters': {
        'simple': {
            'format': '%(levelname)s|%(message)s'
        },

        'verbose': {
            'format': '%(levelname)s|%(asctime)s|%(module)s|%(funcName)s|%(message)s',
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
    },

    'loggers': {
        'skripten_shop': {
            'level': 'DEBUG',
            'handlers': ['default', ],
        }
    },
}

# Crispy Forms Settings
#############################################################
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Django Simple Captcha Settings
# http://django-simple-captcha.readthedocs.io/en/latest/usage.html
#############################################################
SOUTH_MIGRATION_MODULES = {
    'captcha': 'captcha.south_migrations',
}
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_FONT_SIZE = 40

# Mail Setting
#############################################################
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'w00739ef.kasserver.com'
EMAIL_HOST_PORT = '587'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'm03dd7e2'
EMAIL_HOST_PASSWORD = skriptnet_credentials['EMAIL_HOST_PASSWORD']
DEFAULT_FROM_EMAIL = 'skripten@verteiler.cc'

# Deployment Settings
#############################################################
SECURE_HSTS_SECONDS = 31536000  # indicates browsers that future requests for the next year should use only HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
# https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SESSION_COOKIE_AGE
SESSION_COOKIE_AGE = 604800  # The age of session cookies, in seconds. (Hier eine Woche)
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
X_FRAME_OPTIONS = 'DENY'
